name: Deploy to EC2

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Archive project
        run: |
          tar czf majid.tar.gz postcss.config.js package.json next.config.js jsconfig.json src public

      - name: Decode SSH key
        env:
          SSH_PRIVATE_KEY_BASE64: ${{ secrets.SSH_PRIVATE_KEY_BASE64 }}
        run: |
          echo "$SSH_PRIVATE_KEY_BASE64" | base64 --decode > ${HOME}/VFix.pem
          chmod 600 ${HOME}/VFix.pem

      - name: Copy project to server
        uses: appleboy/scp-action@master
        with:
          host: 54.70.76.118
          username: ubuntu
          key: "${{ env.HOME }}/VFix.pem"
          source: "majid.tar.gz"
          target: "~"
          overwrite: true

      - name: Deploy project
        uses: appleboy/ssh-action@master
        with:
          host: 54.70.76.118
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY_BASE64 }}
          script: |
            mkdir majid-temp
            tar xf majid.tar.gz -C majid-temp 2> /dev/null
            rm majid.tar.gz
            cd majid-temp
            find . -name '._*' -exec rm {} \;
            npm i
            npm run build
            cd ..
            rm -rf majid
            mv majid-temp majid
            cd majid
            pm2 delete majid
            pm2 start npm --name "majid" -- start
